### PR TITLE
label coloring / myOpenOrders / left to right direction

### PR DESCRIPTION
**Pull request by c055**

### CODE REVIEW

**Comment by c055** [comment]
myOpenOrders / left to right direction

**Comment by svk31** [comment]
I don't think we should use this left to right direction, I much prefer the way it was.

**Comment by c055** [comment]
:) me too ..

**Comment by c055** [comment]
so how to proceed now?

**Comment by c055** [comment]
@valzav

**Comment by svk31** [comment]
Closing this as it's been a while and there are conflicts now. If you want to you can make another PR with the changes you want to include, but I think we'll keep the cancel buttons on the sides as they are now.

**Pull request closed without merging**
