### PR TITLE
exchange layout

### PR DESCRIPTION
**Pull request by c055**

### CODE REVIEW

**Comment by c055** [comment]
bildschirmfoto 2015-06-23 um 14 16 25

**Comment by c055** [comment]
i'll try to add a screenshot for each pull i'll creating in future so you will be able to see updates without have to test it .. would this make sense to you ?

**Comment by svk31** [comment]
Sure, although we should probably just give you push rights so you can make changes directly without needed to do a PR

**Comment by c055** [comment]
for now i would like to do it in this way, until i'm getting more familiar with UI etc... so i wouldn't not be able to break somthing .. and you will be able to review my updates before merge it ..

**Pull request merged**
