### PR TITLE
myOpenOrders / hover / cancel button

### PR DESCRIPTION
**Pull request by c055**

### CODE REVIEW

**Comment by c055** [comment]
Marketpage Screenshot

**Comment by valzav** [comment]
Can we move Cancel button to the right? The rationale behind this - since we are reading from left to right, things on the left get more attention, so I would place more important data on the lef, e.g. in this ordert: Amount, Price, Expiration (in hours and minutes), Cancel

**Comment by svk31** [comment]
I disagree, this is one place where we definitely should keep the symmetry and it's important to have the prices next to each other. 

Actually I'm not sure we should even keep the expiration column, but because of the placement of the orders there's a lot of horizontal space that we need to fill, that's why they're there atm..

**Comment by c055** [comment]
+1

**Comment by valzav** [comment]
I didn't notice your objective was to put prices side by side to make easier to compare them. But this is only relevant for those users who place both buy and sell order the same time - probably market makers, I think it would be less than 0.1% of all users. So I think consistency is more important that symmetry in this particular case, but this is up to you to decide.

**Pull request merged**
