### PR TITLE
fix for 0 balance returning null instead of a valid component

### PR DESCRIPTION
**Pull request by wildbunny**
the first is a generic fix for the BalanceComponent, the 2nd is adding metaexchange as a gateway and bridge

### CODE REVIEW

**Comment by valzav** [comment]
@wildbunny, we are going to have a release tomorrow (we are on a weekly basis release schedule), do you think your metaexchange integration is production ready? maybe it makes sense to include it into next release after tomorrow's one so we have more time to test?

**Comment by wildbunny** [comment]
It should be ready to go - I've spent most of today testing and fixing :)

**Comment by valzav** [comment]
I'll make a pre-release to bitshares.org/wallet later today and we can ask some community members to test it

**Comment by wildbunny** [comment]
Fantastic :) How can I find out when its live, so I can point shentist at it?

**Comment by valzav** [comment]
I'm getting this error:

```
Fetch API cannot load https://metaexchange.info/api/1/getMarket. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

do you have CORS on a server?

**Comment by wildbunny** [comment]
The 403 response is our API rate limiter - I'll alter the limits

**Comment by valzav** [comment]
not sure this is rate limit, but CORS pre-flight requests can come one after another without delay, so it’s possible that this rate limit

> On Nov 10, 2015, at 3:47 PM, wildbunny notifications@github.com wrote:
> 
> The 403 response is our API rate limiter - I'll alter the limits
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/cryptonomex/graphene-ui/pull/479#issuecomment-155560831.

## 

Regards,
Val

**Comment by wildbunny** [comment]
The normal responses have CORS set - the rate limit is just a plan 403. Are you seeing valid looking stuff, or is everything kind of broken?

**Comment by valzav** [comment]
yes, first call to https://metaexchange.info/api/1/submitAddress https://metaexchange.info/api/1/submitAddress is ok, the next 3 failed

> On Nov 10, 2015, at 3:50 PM, wildbunny notifications@github.com wrote:
> 
> The normal responses have CORS set - the rate limit is just a plan 403. Are you seeing valid looking stuff, or is everything kind of broken?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/cryptonomex/graphene-ui/pull/479#issuecomment-155561705.

## 

Regards,
Val

**Comment by wildbunny** [comment]
For some reason the page seems to load (or at least initialise) twice in quick succession, which is what causes those errors to appear with seemingly no consequences; the first load goes through ok, then the second load triggers the rate limiter.

**Comment by valzav** [comment]
maybe these are CORS pre-flight option requests?

**Comment by wildbunny** [comment]
Stick a breakpoint in the constructor of AccountDepositWithdraw, and hit reload on the page. It gets called twice; I think this is what's causing our rate limiter to fire.

**Comment by valzav** [comment]
I added shouldComponentUpdate to prevent unnecessary rendering - looks like it helped, I'll deploy to bitshares.org/wallet

**Comment by wildbunny** [comment]
Sweet :)

**Comment by valzav** [comment]
please test https://bitshares.org/wallet

**Comment by wildbunny** [comment]
Thanks :)

**Pull request merged**
